package com.example.Portfolio.ProductCatalog.Models;

public enum ProductSubDivision {

    SNEAKERS,BOOTS, SLIPPERS,SANDALS,LOAFERS,FLATS,OXFORDS,HEELS,

    TSHIRTS,DRESSES, PANTS, SHIRTS, SWEATERS, JACKETS, SKIRTS, BLOUSES, JEANS, SUITS, SHORTS,

    HATS, BAGS, JEWELRY, BELTS, SUNGLASSES, GLOVES, WALLETS, WATCHES, SOCKS, TIES
}
